### PR TITLE
Add release-delete

### PR DESCRIPTION
**Pull request by tanho63**
(Ideally #82 is merged first to reduce/avoid conflicts)

TODO:
- [x] Add pb_release_delete() testing
- [x] Review current testing as a whole
- [ ] make all checks pass

### CODE REVIEW

**Comment by tanho63** [comment]
@cboettig working through some test restructures and was curious - where do CBOETTIG_TOKEN-related tests get run (it looks like GHA is skipping them?)

Are appveyor or travis still being tested also?

Would it be possible to add CBOETTIG_TOKEN to repo secrets and making accessible from rcmd check? (I can do the GHA bit if you do the repo secret bit)

**Comment by cboettig** [comment]
Thanks @tanho63 !  

re the `CBOETTIG_TOKEN` infrastructure, might be worth refactoring that a bit.  I have to double-check but I think that token probably expired and wasn't renewed.  More to the point, I think in modern GH-Actions, GH-Actions provides a secure GITHUB_TOKEN secret env var which is unique to the repo and doesn't need manual curation/renewal (although don't recall entirely how permissions work there in PRs etc...).  Presumably the tests could use that, might need to read up on the config again....

**Comment by tanho63** [comment]
Okay, no problem, that would somewhat mean making a "mess" of the ropensci/piggyback releases (but having the `pb_release_delete` feature is useful there!)

**Comment by tanho63** [comment]
https://github.com/ropensci/piggyback/settings/actions + 
image

should be sufficient to grant permissions to the releases in this repo

**Comment by cboettig** [comment]
cool, looks like these are already set:

image

**Comment by tanho63** [comment]
_crosses fingers_ 🤞

It may make more sense to switch testing to a private repository eventually, any failed tests may leave the release history within this repo a bit of a mess?

Edit: lol it failed. It looks like there isn't permission to create new releases
image


Putting in a personal token may be the way to go, perhaps.

**Comment by cboettig** [comment]
@tanho63 sounds like a good plan.  You should have just gotten an invite as a maintainer on the repo, lemme know if that has the right permission level for you to add a token?

**Comment by tanho63** [comment]
Hmm. It’s not passing secret in, I think because it’s from a forked repo atm. Will keep poking at it

**Comment by tanho63** [comment]
Closing - cannot use repo secret in PR from my fork. PR #85 hopefully will be the one that works

**Pull request closed without merging**
