### PR TITLE
fix bug in auth header

### PR DESCRIPTION
**Pull request by tanho63**
Introduced a bug because I forgot to use Authorization in the header. Probably should have a better look at all the tests before next CRAN release

### CODE REVIEW

**Comment by tanho63** [comment]
Hmm. I wonder if that check failure is just a bad API response. It would help if the error message returned the HTTP code...

**Review by cboettig — APPROVED** [review]
Looks good.  Thanks for all the continued work here.  Can you also switch your role from `ctb` to `aut` and list your name second in the Authors@R list?

**Comment by cboettig** [comment]
🚀

**Comment by cboettig** [comment]
(apologies for the delay, was away from 💻  for a bit)

**Pull request merged**
